-- Darth Beer.com データ更新パイプライン シード
-- 目的     : 候補 31件 の反映 (新規 31件 / 更新 0件)。仕様§6 データ更新パイプライン
-- 対象DB   : dev = beer_dev / 本番昇格時 = beer
-- 種別     : DML のみ (DDL を含まない)
-- 冪等性   : deploy/apply_sql.php が schema_migrations(filename + sha256)で二重適用を防ぐ。
--            適用済みのこのファイルは書き換えないこと(内容の改変は runner が検知して拒否する)。
--            直し直すときは新しい番号のファイルを作る。
-- 生成元   : scripts/make_sql.py / run_id=20260827 / seq=003
--            候補ファイル = /workspace/tool/beer/beer-data-work/candidates3-ship.json
-- 生成日時 : 2026-08-27 00:10:51
-- 巻き戻し : 003_seed_20260827_rollback.sql
-- 適用     : remote_sql.sh dev --apply <このファイル> --dry-run  で件数を確認してから本適用
--            (このパイプラインは DB を直接書き換えない。適用は必ず runner 経由)
-- 文字コード : SET NAMES は書かない。runner が DSN の charset=utf8mb4 を検査して保証する

-- mk0019: いわて蔵ビール (c-maker-sekinoichi)
INSERT INTO `maker` (`MakerID`, `MakerName`, `MakerExplain`, `URL1`, `country_code`, `latitude`, `longitude`, `logo_path`, `source_url`, `logo_rights`) VALUES ('mk0019', 'いわて蔵ビール', '岩手県一関市に蔵を構える世嬉の一酒造が展開するビールブランド。母体となる会社は1918年の創業で、清酒づくりを本業としてきた。いわて蔵ビールは1995年に市内の有志と共同で立ち上げられ、翌1996年から販売が始まっている。', 'https://sekinoichi.co.jp/', 'JP', 38.931593, 141.132968, NULL, 'https://sekinoichi.co.jp/company/', 'none');

-- mk0023: 富士桜高原麦酒 (d-maker-fujizakura)
INSERT INTO `maker` (`MakerID`, `MakerName`, `MakerExplain`, `URL1`, `country_code`, `latitude`, `longitude`, `logo_path`, `source_url`, `logo_rights`) VALUES ('mk0023', '富士桜高原麦酒', '山梨県南都留郡富士河口湖町船津、富士山の北側の裾野にあたる標高1000mの土地に醸造所を置くブリュワリー。運営は富士観光開発株式会社で、醸造の始まりは1997年。仕込みには富士山麓の軟水を用いている。ブルワリー・オブ・ザ・イヤーでは2011年にウェルタースケール部門、2014年にミドルスケール部門で金賞を受けている。', 'https://www.fujizakura-beer.jp', 'JP', 35.485401, 138.76709, NULL, 'https://www.fujizakura-beer.jp/about/', 'none');

-- mk0026: スワンレイクビール (d-maker-swanlake)
INSERT INTO `maker` (`MakerID`, `MakerName`, `MakerExplain`, `URL1`, `country_code`, `latitude`, `longitude`, `logo_path`, `source_url`, `logo_rights`) VALUES ('mk0026', 'スワンレイクビール', '新潟県阿賀野市に拠点を置くブリュワリー。運営は株式会社天朝閣で、1997年にビール蔵を開いて醸造を始めた。仕込みを行う施設には瓢湖屋敷の杜ブルワリーの名がある。本社の所在地は醸造所とは別で、同市中島町に置かれている。', 'https://www.swanlake.co.jp/main/', 'JP', 37.829515, 139.26207, NULL, 'https://www.swanlake.co.jp/main/outline/', 'none');

-- mk0030: 宮下酒造 (e-maker-miyashitashuzo)
INSERT INTO `maker` (`MakerID`, `MakerName`, `MakerExplain`, `URL1`, `country_code`, `latitude`, `longitude`, `logo_path`, `source_url`, `logo_rights`) VALUES ('mk0030', '宮下酒造', '岡山市中区西川原に蔵を置く造り手。酒づくりの始まりは1915年で、1922年に宮下酒造合名会社として法人の形をとった。1965年には現在地に酒造工場を新築し、拠点をまるごと移している。ビールも手がけており、その銘柄には「独歩」の名が冠されている。', 'https://www.msb.co.jp', 'JP', 34.678814, 133.940338, NULL, 'https://www.msb.co.jp/aboutus/', 'none');

-- pr0038: シュバルツ (b-baeren-schwarz)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0038', 'mk0008', 'シュバルツ', 'st0011', 5.5, 26.0, NULL, 8, NULL, NULL, NULL, 'ベアレンが通年で並べる定番銘柄のひとつ。シュバルツはドイツ語圏で黒を指すときに使う語で、それがそのまま名前になっている。原料は麦芽とホップのみで、副原料に頼らない簡素な構成をとる。ロースト由来の香りが立ち、液色は深い側にある。口当たりはまろやかで、あと味はすっきりと引いていく。飲みやすさの側に軸足を置いた造りといえる。', 26, NULL, 'https://baeren.jp/products/schwarz', 'placeholder', 'https://baeren.jp/products/schwarz', 'IBU_all,Color');

-- pr0039: 金色堂ゴールデンエール (c-sekinoichi-kinkuragoldenale)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0039', 'mk0019', '金色堂ゴールデンエール', 'st0097', NULL, 30, NULL, NULL, NULL, 2, NULL, '世界文化遺産に登録された平泉・中尊寺の金色堂。その記念として名を与えられたのが、世嬉の一酒造が岩手・一関で醸す「いわて蔵ビール」の定番、このゴールデンエールである。使われるヨーロピアンホップはグレープを思わせる気配とフローラルな広がりをもたらし、飲み口はさっぱりと、後を引かずスッキリまとまる。インターナショナルビアコンペティションでは2014年に金賞を受けた。度数と苦味の数値は公式には公開されていない。', 30, NULL, 'https://sekinoichi.co.jp/beer/', 'placeholder', 'https://sekinoichi.co.jp/beer/', 'IBU_all,Fruity');

-- pr0040: ケラ・ピルカ (c-taisetsujibeer-kelapiruka)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0040', 'mk0020', 'ケラ・ピルカ', 'st0007', 5.0, 30, NULL, NULL, NULL, 2, NULL, '銘柄名の「ケラ・ピルカ」は、アイヌ語で「美味しい」を指す言葉からとられている。大雪地ビールが英国系のペールエールとして仕込む一本で、酵母に由来するフルーティーな香りが立ちのぼる。口に含むとまずキレのよさが立ち、飲み下したあとに麦芽の甘みがゆるやかに残る。度数はエールとして標準的な範囲に置かれており、苦味の数値は公式には公開されていない。', 30, NULL, 'https://craft.ji-beer.com/product/kela-piruka/', 'placeholder', 'https://craft.ji-beer.com/product/kela-piruka/', 'IBU_all,Fruity');

-- pr0043: PILS (d-fujizakura-pils)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0043', 'mk0023', 'PILS', 'st0069', 5.0, 30, 30, NULL, NULL, NULL, NULL, '富士桜高原麦酒が定番シリーズに置くジャーマン・ピルスナー。この一杯でまず輪郭を決めているのは切れ上がりの良さで、飲み下したあとに重さを残さない。その手前を支えるのが麦芽の風味で、痩せた印象にならないだけの厚みが敷かれている。香りはハーバルな草の気配とフローラルな華やぎが同居し、鼻先で強く主張するというより全体の輪郭を整える側に回る。苦みはそこへ芯を一本通す位置に据えられ、飲み口を引き締めている。派手な仕掛けではなく、素材どうしの噛み合わせで骨格を立てたドイツ系ラガーである。', 37.5, NULL, 'https://www.fujizakura-beer.jp/beers/?id=beers_pils', 'placeholder', 'https://www.fujizakura-beer.jp/beers/?id=beers_pils', NULL);

-- pr0046: アンバースワンエール (d-swanlake-amberswanale)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0046', 'mk0026', 'アンバースワンエール', 'st0003', 5.0, 45, 45, 5, 1, 2, NULL, '新潟・阿賀野の瓢湖屋敷の杜ブルワリーが手がけるアンバーエール。グラスの中では澄んだ琥珀色が静かに沈み、光を通すと赤みを帯びて見える。香りは華やかなホップとモルトの旨みが同居し、甘みと苦味のどちらにも寄りきらないバランスに落とし込まれている。アメリカンスタイルのアンバーエールに位置づけられる一本で、World Beer Awards での受賞歴を持つ定番でもある。焼き目のついた料理と合わせても、輪郭が崩れにくい厚みがある。', 35, NULL, 'https://www.swanlake.co.jp/main/beer/', 'placeholder', 'https://www.swanlake.co.jp/main/beer/', 'Color,Clarity,Fruity');

-- pr0048: KIRISHIMA BEER STOUT （スタウト） (e-kirishima-stout)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0048', 'mk0028', 'KIRISHIMA BEER STOUT （スタウト）', 'st0052', 5.0, NULL, NULL, NULL, NULL, NULL, NULL, '焼酎づくりで知られる霧島酒造が手がけるビールの一本。仕込みを担うのは、蔵の直営施設のなかに置かれた霧の蔵ブルワリーである。銘柄が名に掲げるスタウトは黒ビールの系統を指す呼び名で、この一本もその流れに位置づけられる。熱処理を経ない生ビールとして仕上げられ、苦味の数値は公開されていない。', 35, NULL, 'https://www.kirishima-fg.jp/post_beer/stout', 'placeholder', 'https://www.kirishima-fg.jp/post_beer/stout', NULL);

-- pr0050: デュンケル瓶 (e-doppo-dunkel)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0050', 'mk0030', 'デュンケル瓶', 'st0009', 5.0, 20.5, NULL, 7, NULL, NULL, NULL, '岡山の宮下酒造が「独歩」の名で並べるデュンケル。原料に立つのは麦芽とホップだけで、その麦芽の一部に焦がしたものを充てているところが、この一本の造りの核になる。飲み口は濃厚な側に寄り、ホップの苦味は強く張らずに一歩下がった位置へ収められている。鼻に届くのは甘みと香ばしさで、そのぶん麦芽の性格がそのまま前へ出る。液の色はブラウン、それも濃褐色と呼ぶべき深さにある。', 20.5, NULL, 'https://www.msb.co.jp/product/1334/', 'placeholder', 'https://www.msb.co.jp/product/1334/', 'IBU_all,Color');

-- pr0051: Rising Sun Pale Ale (d-baird-risingsunpaleale)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0051', 'mk0022', 'Rising Sun Pale Ale', 'st0004', 5.5, 34, 34, 3, NULL, 2, NULL, 'ペレットにもエキスにも頼らず、全粒のホールフラワーホップだけでドライホップを行うのが、この銘柄の造りの軸になっている。使われるのは米国太平洋岸北西部産のホップで、柑橘の輪郭と松の樹脂を思わせる香りは、その産地の性格から来ている。苦味は中庸の位置に収められ、度数も張り上げられていない。銘柄名は、日出づる国としての日本と、その象徴である富士山にちなむ。Baird Brewing が手がける、ペールエールの一本。', 40, NULL, 'https://bairdbeer.com/products/rising-sun-pale-ale', 'placeholder', 'https://bairdbeer.com/products/rising-sun-pale-ale', 'Color,Fruity');

-- pr0052: Freshly Squeezed (a-freshly-squeezed)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0052', 'mk0002', 'Freshly Squeezed', 'st0093', 8.0, 50, NULL, 4, 4, 3, NULL, 'ギャラクシー、モザイク、シトラ CRYO を重ねて仕込まれたジューシー系のダブルIPA。口当たりはシルキーで、そのなめらかさの上へ柑橘の皮を思わせる苦みが薄く重なる。香りは果肉の甘さと酸が入り混じる方向にあり、メロンやキウイの丸みに、パイナップルとグレープフルーツの張りが加わって、イエロースターバーストのような菓子めいた甘さまで顔を出す。ヘイジーと呼ばれる濁りをまとった液体で、度数は高い側に取られている。', 50, NULL, 'https://www.westcoastbrewing.jp/beer/freshly-squeezed/', 'placeholder', 'https://www.westcoastbrewing.jp/beer/freshly-squeezed/', 'IBU_all,Color,Clarity,Fruity');

-- pr0053: Osmunda (a-osmunda)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0053', 'mk0004', 'Osmunda', 'st0093', 6.5, 20, 20, 4, 4, 3, NULL, 'VERTERE が仕込むヘイジーIPA。ホップはコヒアネルソンとリワカの二種で、香りにはグレープフルーツの爽やかさ、マンゴーの丸み、パッションフルーツの華やぎが並ぶ。麦芽はエクストラペールのプレミアムピルスナーモルトとカラピルスに、フレークドオーツと小麦麦芽を加えた構成。この穀物の組み合わせが、なめらかでクリーミーな口当たりを生む土台になっている。苦味は前に出るというより輪郭を支える位置に置かれ、香りと質感で運ぶ設計がうかがえる。', 50, NULL, 'https://verterebrew.com/brewlog/osmunda/', 'placeholder', 'https://verterebrew.com/brewlog/osmunda/', 'Color,Clarity,Fruity');

-- pr0055: クラシック (b-baeren-classic)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0055', 'mk0008', 'クラシック', 'st0067', 6.0, 26.0, NULL, NULL, NULL, NULL, NULL, 'ベアレンが通年で並べる定番で、スタイルはドイツのドルトムントに由来するドルトムンダー。醸造にはドイツから移設した100年以上前の設備が使われている。「世界に伝えたい日本のクラフトビール」コンテストでは初代のグランプリを受けた。原料は麦芽とホップだけ。飲み飽きしにくさが持ち味で、それを支えているのは苦みとコクがどちらにも傾かない配置である。度数はこの系統としてはやや高めに取られている。', 26, NULL, 'https://baeren.jp/products/classic', 'placeholder', 'https://baeren.jp/products/classic', 'IBU_all');

-- pr0062: ペールエール (b-hitachino-pale-ale)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0062', 'mk0016', 'ペールエール', 'st0004', 5.5, 45, 45, 3, NULL, NULL, NULL, '麦芽とホップだけで組み立てられた、常陸野ネストビールのアメリカンペールエール。この一本でいちばん強く出るのは香りで、ほかのどの要素よりも高い位置に置かれている。向かう先はフローラルな方向。コクは厚めに取られる一方、苦味は中庸にとどまり、酸味とキレは低く抑えられているため、口の中に留まる時間が長い。香りの端には爽やかさも差し、液色は淡い側にある。', 40, NULL, 'https://kiuchibrewery.co.jp/products/beer/list/pale-ale/', 'placeholder', 'https://kiuchibrewery.co.jp/products/beer/list/pale-ale/', 'Color');

-- pr0063: Pineapple Party (a-pineapple-party)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0063', 'mk0002', 'Pineapple Party', 'st0093', 5.0, 50, NULL, 4, 4, 3, NULL, '副原料にパイナップルピューレを用いた、West Coast Brewing のセッション強度のヘイジーIPA。口当たりはなめらかで、ジューシーな甘さが乗りながらも飲み口そのものは軽い側に置かれている。香りには刈りたての草のような青い気配が混じり、そこへトロピカルフルーツの甘やかさと柑橘の輪郭が並び立つ。ドライホップに使われているのはエルドラド、アイダホ7、ルミノーサの三種で、度数も控えめに取られている。', 50, NULL, 'https://www.westcoastbrewing.jp/beer/pineapple-party/', 'placeholder', 'https://www.westcoastbrewing.jp/beer/pineapple-party/', 'IBU_all,Color,Clarity,Fruity');

-- pr0064: 道後ビール スタウト(漱石ビール) (e-dogo-stout)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0064', 'mk0029', '道後ビール スタウト(漱石ビール)', 'st0052', 5.0, NULL, NULL, 9, NULL, NULL, NULL, '水口酒造が手がける道後ビールのうちの一本で、「漱石ビール」の愛称で呼ばれる。熱処理を行わず、酵母を残したまま仕上げる生ビールである。原料は麦芽とホップ、そこに麦を加えた構成で、麦芽はドイツ製造とカナダ製造のものが軸を占める。液色は黒。香りには焙煎した穀物のような香ばしさが立ち、口に含めば苦味がその香りと同じ方向へ伸びる。苦味の数値は公開されていないが、ローストと苦味の二本だけで輪郭を描く、飾りの少ないスタウトといえる。', 35, NULL, 'https://minakuchi-shuzo.jp/products/%E9%81%93%E5%BE%8C%E3%83%93%E3%83%BC%E3%83%AB-%E3%82%B9%E3%82%BF%E3%82%A6%E3%83%88-%E6%BC%B1%E7%9F%B3%E3%83%93%E3%83%BC%E3%83%AB', 'placeholder', 'https://minakuchi-shuzo.jp/products/%E9%81%93%E5%BE%8C%E3%83%93%E3%83%BC%E3%83%AB-%E3%82%B9%E3%82%BF%E3%82%A6%E3%83%88-%E6%BC%B1%E7%9F%B3%E3%83%93%E3%83%BC%E3%83%AB', 'Color');

-- pr0066: 横浜ラガー (c-yokohamabeer-yokohamalager)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0066', 'mk0021', '横浜ラガー', 'st0088', 5.0, 45, 45, NULL, NULL, 2, NULL, '横浜ビールが、自らの名と同じ地名をそのまま冠したラガー。苦味はラガーとしては高めの水準に置かれており、飲み口の芯にはっきりとした軸が通る。味わいの側には麦芽が据えられていて、含んだあとから香ばしさがゆっくり広がっていく。香りはといえば柑橘の方向に振れていて、ホップが前に出る。ラガーらしい素直さを保ちながら、苦味と香りの双方に手を伸ばした設計と言える。缶で展開される定番の一本。', 35, NULL, 'https://yokohamabeer.com/products/', 'placeholder', 'https://yokohamabeer.com/products/', 'Fruity');

-- pr0068: RAUCH (d-fujizakura-rauch)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0068', 'mk0023', 'RAUCH', 'st0010', 5.5, 21, 21, NULL, NULL, NULL, NULL, 'ブナ材で燻した麦芽を用いて仕込まれる、バンベルクに伝わるラオホビアの流れをくむ一本。香りは燻煙が中心を占める。味わいの側ではスモーキーさとモルトの甘さが並び立ち、苦味は控えめな側に置かれることで、燻した麦芽の個性が前に出る配置になっている。富士桜高原麦酒が定番シリーズのひとつとして続けている銘柄で、2012年には World Beer Cup と World Beer Awards の両方で賞を受けている。', 21.5, NULL, 'https://www.fujizakura-beer.jp/beers/?id=beers_rauch', 'placeholder', 'https://www.fujizakura-beer.jp/beers/?id=beers_rauch', NULL);

-- pr0070: W-IPA (d-minoh-wipa)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0070', 'mk0025', 'W-IPA', 'st0094', 9.0, 60, NULL, 6, NULL, 2, NULL, 'モルトもホップも通常の仕込みを大きく超える量で投じる、箕面ビールの高アルコールなIPA。グラスに現れるのは濃い銅色で、アメリカンホップのフルーティな香りがそこから立つ。口に含めばモルトの厚みと苦味が正面から組み合い、原料は麦芽とホップだけという簡素さのまま密度だけが増していく。World Beer Awards では2013年に、International Brewing Awards では2017年に、それぞれ世界金賞を受けている。公式に苦味の数値は示されていない。', 60, NULL, 'https://store.minoh-beer.jp/products/w-ipa', 'placeholder', 'https://www.minoh-beer.jp/products/w-ipa/', 'IBU_all,Color,Fruity');

-- pr0071: スワンレイクIPA (d-swanlake-ipa)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0071', 'mk0026', 'スワンレイクIPA', 'st0090', 7.0, 55, 55, 4, 1, 2, NULL, '瓢湖屋敷の杜ブルワリーの定番IPA。金色から琥珀色にかけての澄んだ液色で、注いだそばからフローラルなホップの香りが強く立つ。苦味はしっかりと据えられているが、麦の厚みがそれを受け止めるため飲み口は荒れない。度数はやや高めに取られており、勢いで空けるより時間をかけて向き合いたいタイプ。冷やしすぎると香りが閉じてしまうので、少し温度が上がってからの表情まで含めて楽しみたい一本である。', 50, NULL, 'https://www.swanlake.co.jp/main/beer/', 'placeholder', 'https://www.swanlake.co.jp/main/beer/', 'Color,Clarity,Fruity');

-- pr0072: 森閑のペールエール (e-hideji-moriaka-paleale)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0072', 'mk0027', '森閑のペールエール', 'st0004', 5.0, 35.0, 35.0, NULL, NULL, 2, NULL, '宮崎ひでじビールが定番として並べるペールエール。ホップにはカスケードを用い、柑橘の香りが軸に据えられている。苦味は輪郭を保つ位置に置かれ、度数も高くは取られていない。醸造所が建つのは延岡の市街地から車で20分ほどの場所で、清流が流れ、森に囲まれ、行縢山が近い土地である。', 40, NULL, 'https://hideji-beer.jp/lineup/', 'placeholder', 'https://hideji-beer.jp/lineup/', 'Fruity');

-- pr0075: ヴァイツェン瓶 (e-doppo-weizen)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0075', 'mk0030', 'ヴァイツェン瓶', 'st0100', 5.0, 20, NULL, NULL, NULL, NULL, NULL, '小麦麦芽を全体の半分以上に用い、大麦麦芽とホップを合わせて上面発酵で仕込むヴァイツェン。酵母を取り除かずにそのまま含ませた造りで、香りにはフェノール由来の要素が立ち、そこがこの銘柄の目印になっている。宮下酒造が独歩の名で送り出す一本で、全国酒類コンクールの地ビール部門では2012年春季・2017年春季・2020年秋季と三度にわたって第1位に選ばれ、2008年秋季には特別奨励賞を受けている。2021年には全国地ビール品質審査会でも入賞している。', 20, NULL, 'https://www.msb.co.jp/product/1348/', 'placeholder', 'https://www.msb.co.jp/product/1348/', 'IBU_all');

-- pr0079: Chill Pils (a-chill-pils)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0079', 'mk0002', 'Chill Pils', 'st0088', 5.0, 35.0, NULL, NULL, NULL, 2, NULL, 'West Coast Brewing が手がけるラガー。香りの構成は幅広く、蜂蜜のような甘さが最初に立ち、その周りを青葉とレモングラスの青い匂いが囲む。奥には緑茶に近い渋みの気配があり、レモンの明るさがそこに重なる。土台になっているのはクラッカーやパンといった焼けた穀物の側の香りで、これが全体を下から支えている。度数は標準的な水準にあり、夏に向けた一本として並べられている。', 35, NULL, 'https://www.westcoastbrewing.jp/beer/chill-pils/', 'placeholder', 'https://www.westcoastbrewing.jp/beer/chill-pils/', 'IBU_all,Fruity');

-- pr0080: マイボック (b-baeren-maibock)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0080', 'mk0008', 'マイボック', 'st0055', 7.0, 29, NULL, NULL, NULL, 2, NULL, 'ベアレンが春の季節限定として仕込むボック。原料は麦芽とホップだけで、通常のビールの倍以上という期間を熟成に充てる長期熟成の造りをとる。香りの側には柑橘が差し、味わいの側は重心が低い。甘みとコクが飲み口の芯をつくり、苦みは控えめな位置から輪郭を縁取る。度数は高めに取られていて、ボックの名にふさわしい飲みごたえがある。', 29, NULL, 'https://baeren.jp/products/maibock', 'placeholder', 'https://baeren.jp/products/maibock', 'IBU_all,Fruity');

-- pr0081: ホッピング シャチ (b-ymarket-hopping-shachi)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0081', 'mk0009', 'ホッピング シャチ', 'st0088', 5.5, 34.03, 34.03, 2, 1, 2, NULL, 'Y.MARKET BREWING が手がけるピルスナー。まず立つのは苦みで、のどごしは軽く、キレのよさが後に残る。グラスに満ちるのは透き通ったゴールド。ホップは Simcoe に Citra と Ekuanot のクライオを重ねた三種構成で、香りは柑橘の輪郭にスパイスの気配が混ざり、その奥からパイナップルとリンゴが顔を出す。アメリカ産ホップの香りを、下面発酵の骨格にのせた造り。', 35, NULL, 'https://craftbeer.nagoya/gallery/%e3%83%9b%e3%83%83%e3%83%94%e3%83%b3%e3%82%b0-%e3%82%b7%e3%83%a3%e3%83%81/', 'placeholder', 'https://craftbeer.nagoya/gallery/%e3%83%9b%e3%83%83%e3%83%94%e3%83%b3%e3%82%b0-%e3%82%b7%e3%83%a3%e3%83%81/', 'Color,Clarity,Fruity');

-- pr0083: Anemone (a-anemone)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0083', 'mk0004', 'Anemone', 'st0004', 5.5, 30, 30, NULL, NULL, 2, NULL, 'VERTERE が手がけるアメリカンペールエール。ピルスナー、マリスオター、カラピルスという三種の麦芽にカスケードとチヌークのホップを重ね、アメリカンエール酵母で発酵させている。味わいの側では苦味が骨格をつくり、麦芽由来の甘味がその内側を満たす。香りの軸になるのは柑橘の爽やかさで、刈りたての草のような青い気配と、花を思わせる甘やかさがそこへ寄り添う。原料の一つひとつは奇をてらわないが、苦味と香りのどちらにも寄りきらない位置で釣り合いを取った造りといえる。', 40, NULL, 'https://verterebrew.com/brewlog/anemone/', 'placeholder', 'https://verterebrew.com/brewlog/anemone/', 'Fruity');

-- pr0084: ペールエール（缶） (b-isekado-pale-ale)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0084', 'mk0013', 'ペールエール（缶）', 'st0004', 5.0, 35, 35, NULL, NULL, 2, NULL, '伊勢角屋麦酒が創業以来つくり続けている看板銘柄。大麦麦芽とホップだけを使う簡素な構成で、そのぶんホップの持ち味が素直に表に出る。含んだ瞬間に広がるのはコクで、そこへ甘味が重なり、苦味は全体を締める側に回る。飲み下したあとはさっぱりと引いていく。香りはパッションフルーツの甘やかさとグレープフルーツの爽やかさが並び、果実の方向を向いている。', 40, NULL, 'https://www.biyagura.jp/c/allitems/0001', 'placeholder', 'https://www.biyagura.jp/c/allitems/0001', 'Fruity');

-- pr0085: アンバーエール (b-hitachino-amber-ale)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0085', 'mk0016', 'アンバーエール', 'st0003', 6.0, 30.0, 30.0, 7, NULL, NULL, NULL, '常陸野ネストビールが麦芽とホップだけで仕込むアメリカンアンバーエール。液色は赤みの差した褐色で、濃さのある側に沈む。香りは華やかで、その強さがこの一本の目印になっている。奥には甘さの含みがあり、焼けた穀物の香ばしさもそこに顔を出す。苦味ははっきりと効き、麦芽の厚みと正面から噛み合う。飲み込んだあとの切れ味は鋭すぎず、余韻がしばらく残る。度数もやや高めに取られた、腰を据えて向き合いたい一本。', 35, NULL, 'https://kiuchibrewery.co.jp/products/beer/list/amber-ale/', 'placeholder', 'https://kiuchibrewery.co.jp/products/beer/list/amber-ale/', 'Color');

-- pr0087: HEFE WEIZEN (c-yokohamabeer-hefeweizen)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0087', 'mk0021', 'HEFE WEIZEN', 'st0100', 5.5, 8, 8, NULL, NULL, 3, NULL, '横浜ビールが瓶詰めの定番として並べるヴァイツェン。ホップの苦味はほとんど前へ出ず、空いた場所を埋めるのは酵母のはたらきである。味わいはフルーティーな方向へまとまり、香りにはバニラの丸みとバナナの甘やかさが重なる。その香りの出どころはドイツ由来の酵母で、麦芽の側でもホップの側でもないところに、この銘柄の輪郭が置かれている。', 20, NULL, 'https://yokohamabeer.com/products/', 'placeholder', 'https://yokohamabeer.com/products/', 'Fruity');
