-- Darth Beer.com データ更新パイプライン シード
-- 目的     : 候補 42件 の反映 (新規 42件 / 更新 0件)。仕様§6 データ更新パイプライン
-- 対象DB   : dev = beer_dev / 本番昇格時 = beer
-- 種別     : DML のみ (DDL を含まない)
-- 冪等性   : deploy/apply_sql.php が schema_migrations(filename + sha256)で二重適用を防ぐ。
--            適用済みのこのファイルは書き換えないこと(内容の改変は runner が検知して拒否する)。
--            直し直すときは新しい番号のファイルを作る。
-- 生成元   : scripts/make_sql.py / run_id=20260828 / seq=005
--            候補ファイル = /workspace/tool/beer/beer-data-work/candidates-3b-all.json
-- 生成日時 : 2026-08-28 04:51:35
-- 巻き戻し : 005_seed_20260828_rollback.sql
-- 適用     : remote_sql.sh dev --apply <このファイル> --dry-run  で件数を確認してから本適用
--            (このパイプラインは DB を直接書き換えない。適用は必ず runner 経由)
-- 文字コード : SET NAMES は書かない。runner が DSN の charset=utf8mb4 を検査して保証する

-- st0103: Cold IPA (style-st0103)
INSERT INTO `style` (`StyleID`, `FamilyName`, `StyleName`, `IBU`, `StyleExplain`, `catchcopy`) VALUES ('st0103', 'IPA', 'Cold IPA', 60, '2018年ごろに米国オレゴン州で生まれた、比較的新しいIPAの一系統。上面発酵のIPAでありながらラガー酵母を使う、あるいは低温側の発酵を行うのが特徴で、そこから『コールド』の名がついた。副原料に米やコーンを加えて麦芽由来の甘みを削ぎ落とし、すっきりとキレのある飲み口に仕上げる造り手が多い。似た名前を持つIPL(インディア・ペール・ラガー)はラガーの系統に分類されるのに対し、コールドIPAはあくまでIPAの一系統として扱われる点が異なる。ホップの香りと苦味はIPAらしくしっかりと立てながら、酵母や副原料の働きで軽やかな後味を狙う、ハイブリッドな性格を持つスタイルである。', 'ラガー酵母で仕込む冷たいIPA');

-- st0104: Brut IPA (style-st0104)
INSERT INTO `style` (`StyleID`, `FamilyName`, `StyleName`, `IBU`, `StyleExplain`, `catchcopy`) VALUES ('st0104', 'IPA', 'Brut IPA', 30, '2017年ごろに米国サンフランシスコで生まれたIPAの一系統。仕込みの過程で糖化酵素を働かせ、麦汁に残る糖分をほぼゼロまで切り詰めるのが最大の特徴で、そのぶん甘みを持たないきりっとした辛口の飲み口に仕上がる。見た目は泡立ちが細かく、色合いも澄んだ淡い金色になりやすいことから、シャンパンになぞらえて語られることもある系統である。ホップの香りは残しつつ苦味は控えめにまとめる造り手が多く、甘さに頼らずキレで飲ませる設計が骨格になっている。IPAの中でも比較的新しく生まれたスタイルであり、造り手によって糖化酵素の使い方や仕上げの辛さの度合いに幅がある。食事と合わせる場面でも、油分の多い料理の後口をさっぱりまとめる役割を果たしやすい。', '辛口を極めたシャンパンIPA');

-- st0105: White IPA (style-st0105)
INSERT INTO `style` (`StyleID`, `FamilyName`, `StyleName`, `IBU`, `StyleExplain`, `catchcopy`) VALUES ('st0105', 'IPA', 'White IPA', 45, '小麦麦芽にコリアンダーシードやオレンジピールを加えるベルジャンホワイト(ヴィットビア)の製法と、ホップを効かせたIPAの製法を掛け合わせた系統。麦のまろやかさとスパイス・柑橘の香りという白ビールらしい下地の上に、IPAならではの強めのホップアロマと苦味を重ねるのが特徴で、単なる小麦ビールよりも苦味の輪郭がはっきりしている。既存のベルジャン・スタイル・ヴィットビアやホワイトエールが苦味を控えめに仕上げるのに対し、こちらはIPAの骨格を保ったまま白ビールの副原料を取り込んでいる点が異なる。ブルワーの実験的な発想から生まれることが多く、造り手によってホップの主張の強さに幅がある。', '白ビール×IPAの実験作');

-- st0106: Radler (style-st0106)
INSERT INTO `style` (`StyleID`, `FamilyName`, `StyleName`, `IBU`, `StyleExplain`, `catchcopy`) VALUES ('st0106', 'Specialty Beers', 'Radler', 8, 'ドイツで生まれた、ビールと果汁やレモネードを合わせた低アルコールの飲み物を指すスタイル。1922年ごろにミュンヘン近郊で誕生したとされ、ドイツ語圏では特定の銘柄名ではなく一般名詞として定着している古い呼び方である。ベースになるビールに果汁やレモネードを混ぜることでアルコール度数を下げ、甘みと酸味を伴う軽い口当たりに仕上げるのが基本の考え方で、暑い時期に喉を潤す飲み物として親しまれてきた。使う果汁の種類は地域や造り手によってさまざまで、柑橘系からベリー系、国内では地場産の果実を使う例も見られる。ビール由来の香味を土台にしながら、果実の酸味や甘みが前面に出るぶん、ビールそのものの苦味や香りは控えめになりやすい。', 'ビールと果汁、自転車乗りの一杯');

-- st0107: Barrel-Aged Beer (style-st0107)
INSERT INTO `style` (`StyleID`, `FamilyName`, `StyleName`, `IBU`, `StyleExplain`, `catchcopy`) VALUES ('st0107', 'Specialty Beers', 'Barrel-Aged Beer', NULL, 'ウイスキーやワインなどに使われた木樽で熟成させたビールの総称で、苦味の系統ではなく『熟成という工程』によって括られている点が、このスタイルの成り立ちを理解するうえでの前提になる。ベースとなるビールはバーレイワインやスタウトなど造り手によってさまざまで、熟成前の中身が何であるかは決められていない。樽に閉じ込められていた原酒の香りがまず立ち、続いて木そのものの渋みや樹脂の風味が時間をかけて染み出してくる。段階を追って層を成していくところに、このスタイルならではの重厚さと複雑さが宿る。ベースが多様であるぶん苦味の幅もきわめて広く、他のスタイルのような基準の苦味値は置かれていない。ビアコンペティションでは独立した部門が設けられることもある、工程そのものを核とする分類である。', '樽で仕上げる、工程のスタイル');

-- pr0118: アルト (baeren-alt)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0118', 'mk0008', 'アルト', 'st0040', 5.0, 38.5, NULL, 6, NULL, NULL, NULL, '麦芽の甘みがまず広がり、まろやかさとともに苦みが後を追う味わい。原材料は麦芽とホップのみとシンプルに絞り込まれ、液色は褐色をたたえる。名称はドイツ語で「古い」を意味する言葉に由来している。', 38.5, NULL, 'https://baeren.jp/products/alt', 'placeholder', 'https://baeren.jp/products/alt', 'IBU_all,Color');

-- pr0119: チョコレートスタウト (baeren-choco)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0119', 'mk0008', 'チョコレートスタウト', 'st0049', 6.5, 47.5, NULL, 9, NULL, NULL, NULL, '黒々とした液色に、深く焙煎した麦芽の香ばしさが立つスタウト。原料は麦芽とホップだけでチョコレートは使っていないが、ほろ苦さの中にカカオやビターチョコレートを思わせる風味が潜む。飲み口は濃厚で、どっしりとした余韻を残す。2005年、国内で初めて『チョコレートスタウト』を名乗って世に出た銘柄でもある。', 47.5, NULL, 'https://baeren.jp/products/choco', 'placeholder', 'https://baeren.jp/products/choco', 'IBU_all,Color');

-- pr0120: 2026 チョコレートスタウトヴィンテージ (baeren-chocov2026)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0120', 'mk0008', '2026 チョコレートスタウトヴィンテージ', 'st0048', 9.5, 65.0, NULL, 8, NULL, 2, NULL, '時間をかけた熟成を前提に仕込まれたヴィンテージビール。チョコレート麦芽を使って黒く仕上げたインペリアルスタウトで、ベアレン史上もっとも高いアルコール度数に設計されている。芳醇な香りの奥にカカオの風味が漂い、濃厚な口当たりには干し葡萄に似た甘みも重なる一本。', 65.0, NULL, 'https://baeren.jp/products/chocov2026', 'placeholder', 'https://baeren.jp/products/chocov2026', 'IBU_all,Color,Fruity');

-- pr0121: コーヒースタウト (baeren-coffeestout)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0121', 'mk0008', 'コーヒースタウト', 'st0049', 6.5, 47.5, NULL, NULL, NULL, NULL, NULL, '焙煎香とコクを重ねた、ベアレンのコーヒースタウト。使うコーヒー豆はエチオピア産で、深めに煎り上げてある。麦芽には英国産を用い、その甘みが奥行きを添えながらじんわりと広がっていく。盛岡の食にゆかりのあるブランドとの協業から生まれた一本でもある。', 47.5, NULL, 'https://baeren.jp/products/coffeestout', 'placeholder', 'https://baeren.jp/products/coffeestout', 'IBU_all');

-- pr0122: ドライチョコレートスタウト (baeren-drychoco)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0122', 'mk0008', 'ドライチョコレートスタウト', 'st0052', 4.5, 35.0, NULL, NULL, NULL, 1, NULL, '香ばしいカカオの風味がまず立ち、続いてカラメルのほのかな甘みがにじむ。飲み口はライトで、後味はべたつかず、すっと引く。ホップは強く主張せず、香りとして静かに寄り添う程度に留まる。使用するのは英国産のチョコレート麦芽とロースト大麦、ホップ。英国伝統の濃色エールの系譜に連なるドライスタウトである。', 35.0, NULL, 'https://baeren.jp/products/drychoco', 'placeholder', 'https://baeren.jp/products/drychoco', 'IBU_all,Fruity');

-- pr0123: 姫とリオの乾杯ビール (baeren-himetorio)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0123', 'mk0008', '姫とリオの乾杯ビール', 'st0088', 4.5, 35.0, NULL, NULL, NULL, 2, NULL, '香りはまず華やかさが立ち、そこに果実のようなふんわりとした甘さが重なる一本。使うホップはフランス産で、その個性が香りづけの軸になっている。盛岡市動物公園ZOOMOとのコラボレーションから生まれ、同日発売の『プレミアムラガー』とはラベルだけを違えた関係にある。売上の一部はZOOMOを通じて、野生の二ホンツキノワグマを守る取り組みに役立てられる。', 35.0, NULL, 'https://baeren.jp/products/himetorio', 'placeholder', 'https://baeren.jp/products/himetorio', 'IBU_all,Fruity');

-- pr0124: イーハトーブの海 (baeren-ihatov)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0124', 'mk0008', 'イーハトーブの海', 'st0065', 5.0, 12.0, NULL, NULL, NULL, 2, NULL, '柑橘を思わせる香りに、ほのかな塩気によるミネラル感が重なるソルティラガー。ホップは醸造所そばの畑で採れた岩手県産、塩は三陸・野田村で直煮によってつくられたものを用いる。発酵の期間を長めに取ることで、すっきりとまとまった飲み口に仕上げている。', 12.0, NULL, 'https://baeren.jp/products/ihatov', 'placeholder', 'https://baeren.jp/products/ihatov', 'IBU_all,Fruity');

-- pr0125: かぼすラードラー (baeren-kabosu-radler)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0125', 'mk0008', 'かぼすラードラー', 'st0106', 2.5, 8.0, NULL, NULL, NULL, NULL, NULL, '大分県産のかぼす果汁を使い、香料を加えずに仕立てたラードラー。定番のレモンラードラーがシチリア産レモンを用いるのに対し、このかぼすラードラーは国産の和柑橘を選んでいる。青々しさと酸味、ほのかな渋みが折り重なり、清涼感のある後味はまろやかに引いていく。原材料は麦芽と糖類、かぼす果汁、ホップの四つ。', 8.0, NULL, 'https://baeren.jp/products/kabosu-radler', 'placeholder', 'https://baeren.jp/products/kabosu-radler', 'IBU_all');

-- pr0126: レモンラードラー (baeren-lemon-radler)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0126', 'mk0008', 'レモンラードラー', 'st0106', 2.5, 8.0, NULL, NULL, NULL, 3, NULL, '南ドイツ発祥のラードラーは、ビールをレモネードで割った低アルコールの飲みものを指し、名は「自転車乗り」を意味すると伝わる。ベアレンのこの一本はシチリア産レモン果汁を香料無添加で合わせ、すっきりとした爽やかな飲み口に仕上げている。原材料は麦芽・糖類・レモン果汁・ホップ。', 8.0, NULL, 'https://baeren.jp/products/lemon-radler', 'placeholder', 'https://baeren.jp/products/lemon-radler', 'IBU_all,Fruity');

-- pr0127: クールシップウィーンラガー (baeren-mikkeller)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0127', 'mk0008', 'クールシップウィーンラガー', 'st0012', 5.5, 25.0, NULL, NULL, NULL, NULL, NULL, 'ミッケラーとのコラボレーションが6年目を迎えた記念に仕込まれた、ウィーンラガーの系統に連なる一本。ベアレンが国内で唯一保有する麦汁冷却設備『クールシップ』を使い、通常の煮沸工程ではなくクールシップの段階でホップを加えるドライホッピングを試みている。苦味づけにはBullet、香りづけにはニュージーランド産の新品種Experimental076を用いた。原料はドイツ製造の麦芽とホップのみ。', 25.0, NULL, 'https://baeren.jp/products/mikkeller', 'placeholder', 'https://baeren.jp/products/mikkeller', 'IBU_all');

-- pr0128: ミルクチョコレートスタウト (baeren-milkchoco)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0128', 'mk0008', 'ミルクチョコレートスタウト', 'st0051', 5.0, 20.0, NULL, NULL, NULL, NULL, NULL, 'ロースト香ばしさに乳糖の甘みが重なる、ベアレンのスタウト。名前は『ミルクチョコレート』だが、実際に使っているのは英国産の麦芽とホップ、それに乳糖だけで、チョコレートや香料は加えていない。英国発祥のスタイルを踏まえた仕込みで、素材の組み合わせだけでその甘い印象に近づけている。', 20.0, NULL, 'https://baeren.jp/products/milkchoco', 'placeholder', 'https://baeren.jp/products/milkchoco', 'IBU_all');

-- pr0129: ザ・デイ Nクラシック (baeren-nclassic)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0129', 'mk0008', 'ザ・デイ Nクラシック', 'st0067', 6.0, 26.0, NULL, NULL, NULL, NULL, NULL, 'コクと苦みが柔らかく調和した、親しみやすい飲み口に仕立てられたラガー。原料は麦芽とホップのみとシンプルに絞られている。スタイルとしてはドイツ・ドルトムント発祥のドルトムンダーにあたり、『クラシック』のアレンジ版として位置づけられる『ザ・デイ』シリーズの一本でもある。', 26.0, NULL, 'https://baeren.jp/products/nclassic', 'placeholder', 'https://baeren.jp/products/nclassic', 'IBU_all');

-- pr0130: 三鉄プレミアムラガー2026 (baeren-santetsu)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0130', 'mk0008', '三鉄プレミアムラガー2026', 'st0088', 4.5, 35.0, NULL, NULL, NULL, 2, NULL, '華やかなホップの香りが立ち、苦みとコクのバランスが心地よい一本。原料は麦芽とホップのみとシンプルな構成で、三陸鉄道とのコラボレーションから生まれた商品でもある。売上の一部は同鉄道への寄付にあてられる。', 35.0, NULL, 'https://baeren.jp/products/santetsu', 'placeholder', 'https://baeren.jp/products/santetsu', 'IBU_all,Fruity');

-- pr0131: ザ・デイ TGピルスナー (baeren-tgpilsner)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0131', 'mk0008', 'ザ・デイ TGピルスナー', 'st0088', 4.5, 35.0, NULL, NULL, NULL, NULL, NULL, '麦芽とホップだけを使う、飾りのないシンプルな構成で仕込まれたピルスナー。伝統的な製法にもとづいて醸造されており、キリリとした苦みと、キレのよいのど越しのバランスを大切にしている一本である。', 35.0, NULL, 'https://baeren.jp/products/tgpilsner', 'placeholder', 'https://baeren.jp/products/tgpilsner', 'IBU_all');

-- pr0132: つなぐビール (baeren-tsunagubeer-can)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0132', 'mk0008', 'つなぐビール', 'st0065', 5.0, 12.0, NULL, NULL, NULL, NULL, NULL, 'ベアレンが国産素材だけで仕込む『つなぐビール』シリーズの一本で、公式表記のスタイルは『セッションラガー』。原料は国内製造の麦芽とホップのみといういたってシンプルな構成で、ホップの香りの奥にやわらかな甘みを残す味わいに仕上げている。同じ名を冠しながらスタイルの異なる仕立て違いも存在する、レシピ違いのシリーズのなかの一本である。', 12.0, NULL, 'https://baeren.jp/products/tsunagubeer-can', 'placeholder', 'https://baeren.jp/products/tsunagubeer-can', 'IBU_all');

-- pr0133: つなぐビール 琥珀色のラガー (baeren-tsunagubeer-kohaku)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0133', 'mk0008', 'つなぐビール 琥珀色のラガー', 'st0008', 5.0, 24.0, NULL, 5, NULL, NULL, NULL, '『つなぐビール』シリーズで初めての限定版として登場したアンバーラガー。原料には岩手県産の原料を100%用いた麦芽とホップのみが使われている。名のとおり琥珀色をたたえた液体で、味わいはキレのよさとまろやかさをあわせ持つ。', 24.0, NULL, 'https://baeren.jp/products/tsunagubeer-kohaku', 'placeholder', 'https://baeren.jp/products/tsunagubeer-kohaku', 'IBU_all,Color');

-- pr0134: つなぐビール ソラチエース (baeren-tsunagubeer-sorachi)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0134', 'mk0008', 'つなぐビール ソラチエース', 'st0065', 5.0, NULL, NULL, NULL, NULL, 1, NULL, '「つなぐビール」限定シリーズの第2弾として仕込まれた一本。岩手県産の大麦麦芽を土台に、ソラチエースを単独で用いるシングルホップ構成とし、ダブルドライホッピング製法でホップの個性を重ねている。ヒノキとハーブ、それぞれの香りが立ち上がり、後味はすっきりとまとまる造り。', 12.0, NULL, 'https://baeren.jp/products/tsunagubeer-sorachi', 'placeholder', 'https://baeren.jp/products/tsunagubeer-sorachi', 'Fruity');

-- pr0135: ウルズス (baeren-ursus)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0135', 'mk0008', 'ウルズス', 'st0056', 7.0, 25.0, NULL, NULL, NULL, 2, NULL, '『ウルズス』はラテン語で『強い熊』を意味する語からとられた名でのウィンタービール。年によって麦芽の配合やレシピを変えて造られており、毎年少しずつ表情を変えるのも持ち味のひとつ。フルーティーな香りに、濃厚でまろやか、コクのある味わいが重なる、ヴァイツェンボックらしい飲みごたえを持つ一本。', 25.0, NULL, 'https://baeren.jp/products/ursus', 'placeholder', 'https://baeren.jp/products/ursus', 'IBU_all,Fruity');

-- pr0136: 山葡萄ラードラー (baeren-yamabudo-radler)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0136', 'mk0008', '山葡萄ラードラー', 'st0106', 2.5, 8.0, NULL, NULL, NULL, 3, NULL, 'ベアレンが手がける『ラードラー』。ドイツ発祥のこのスタイルは『自転車乗り』を意味する呼称で、ビールをレモネードで割った低アルコールの飲み物として親しまれてきた。ここでは岩手県野田村産の山葡萄果汁とレモン果汁を合わせ、香料は使わずに仕上げている。山葡萄由来の甘みと酸味に清涼感が重なり、口当たりは芳醇にまとまる一本。', 8.0, NULL, 'https://baeren.jp/products/yamabudo-radler', 'placeholder', 'https://baeren.jp/products/yamabudo-radler', 'IBU_all,Fruity');

-- pr0137: 茜音-Akane- (coedo-akane-2026)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0137', 'mk0007', '茜音-Akane-', 'st0004', 5.0, 40.0, NULL, 5, NULL, 2, NULL, 'COEDO BREWERYが秋の時季に合わせて仕立てるアメリカンペールエール。琥珀色の液体からシトラスとフローラルな香りが立ちのぼり、口に含むと旨みと苦味が層になって広がる。秋の准定番として、これまで複数年にわたり販売が重ねられてきた一本。', 40.0, NULL, 'https://www.coedobrewery.com/products/akane-2026', 'placeholder', 'https://www.coedobrewery.com/products/akane-2026', 'IBU_all,Color,Fruity');

-- pr0138: 青碧-AO- (coedo-ao-2026-cold-ipa)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0138', 'mk0007', '青碧-AO-', 'st0103', 5.5, 60.0, NULL, 2, 1, 1, NULL, '淡い金色でよく澄んだ液色に、ハーバルな香りが漂うコールドIPA。仕込みにはラガー酵母を用いながらも、味の骨格はIPAらしい苦味で組み立てられている。原材料は麦芽とホップのみとシンプルで、2018年に登場したばかりの新しいスタイルらしい、輪郭のはっきりした造りに仕上がっている。', 60.0, NULL, 'https://www.coedobrewery.com/products/ao-2026-cold-ipa', 'placeholder', 'https://www.coedobrewery.com/products/ao-2026-cold-ipa', 'IBU_all,Color,Clarity,Fruity');

-- pr0139: Fresh Hop（フレッシュホップ） (coedo-freshhop2025)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0139', 'mk0007', 'Fresh Hop（フレッシュホップ）', 'st0089', 6.0, 43.1, 43.1, NULL, NULL, 3, NULL, '山梨県北杜市の生産者、小林さん一家が育てた生ホップを収穫当日に仕込みへ投入した、コエドが毎年手がけるフレッシュホップシリーズの一本。使用するのはオリジナル品種『HKTS02』。麦芽とこのホップだけの構成で、マスカットを思わせる瑞々しい香りと、苦味の効いた味わいに仕上がっている。', 40.0, NULL, 'https://www.coedobrewery.com/products/freshhop2025', 'placeholder', 'https://www.coedobrewery.com/products/freshhop2025', 'Fruity');

-- pr0140: 采葉-Iroha- (coedo-iroha-2026-west-coast-ipa)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0140', 'mk0007', '采葉-Iroha-', 'st0084', 5.5, 50.0, NULL, 4, 1, 2, NULL, 'COEDO BREWERYが『采葉-Iroha-』の名で複数年にわたり仕込んできたウエストコーストIPA。原料は麦芽とホップのみのシンプルな構成でありながら、クリーンに澄んだ黄金色の液体からグレープフルーツの香りが立ちのぼる。旨味と苦味がしっかりと感じられる飲み口で、年を重ねながら準定番の位置を築いてきたシリーズの一本である。', 50.0, NULL, 'https://www.coedobrewery.com/products/iroha-2026-west-coast-ipa', 'placeholder', 'https://www.coedobrewery.com/products/iroha-2026-west-coast-ipa', 'IBU_all,Color,Clarity,Fruity');

-- pr0141: 白舞-Shirogamau- (coedo-shirogamau2025)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0141', 'mk0007', '白舞-Shirogamau-', 'st0090', 5.5, 50.0, NULL, 2, 1, 2, NULL, 'もちもちとした滑らかな口当たりが印象に残る一本。オレンジを思わせる香りが立ち上がり、透明感のある薄い金色の液体がグラスを満たす。この香りを生むのはホップ由来のチオールで、通常は酵母が担うエステルの役割を代わりに引き受ける設計になっている。名はドイツのクリスタルヴァイツェンに着想を得たCOEDO BREWERY独自の呼び方で、『クリスタルIPA』と称されるスタイルにあたる。准定番として複数年にわたり造られてきた一本でもある。', 50.0, NULL, 'https://www.coedobrewery.com/products/shirogamau2025', 'placeholder', 'https://www.coedobrewery.com/products/shirogamau2025', 'IBU_all,Color,Clarity,Fruity');

-- pr0142: バレルフカミダス (yoho-barrel)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0142', 'mk0006', 'バレルフカミダス', 'st0107', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ウイスキー樽で寝かせたバーレイワイン。まず原酒由来のコクが舌に乗り、しばらく置いてから樽の木の風味がじわりと滲み出し、後半にかけて重厚さと複雑さが増していく一本。仕込みごとに表情が変わるため、度数や苦みは公式でも一つの数値に定まっていない。', NULL, NULL, 'https://yohobrewing.com/products/barrel/', 'placeholder', 'https://yohobrewing.com/products/barrel/', NULL);

-- pr0143: 軽井沢ビール クラフトザウルス ブラックIPA (yoho-craftsaurus_blackipa)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0143', 'mk0006', '軽井沢ビール クラフトザウルス ブラックIPA', 'st0070', 6.5, 40.0, 40, 9, NULL, NULL, NULL, '『軽井沢ビール クラフトザウルス』シリーズのブラックIPA。ホップの香りを前面に引き出すため麦芽由来の香りをおさえる設計で、殻を取り除いたロースト麦芽『Carafa Special』を採用している。黒く仕上がった液色に、ホップの香りが重なる一本で、ワールド・ビア・アワード2019のカントリーウィナー、インターナショナル・ビアカップ2019の銅賞をそれぞれ受けた。', 60.0, NULL, 'https://yohobrewing.com/products/craftsaurus_blackipa/', 'placeholder', 'https://yohobrewing.com/products/craftsaurus_blackipa/', 'Color');

-- pr0144: 軽井沢ビール クラフトザウルス ブリュットIPA (yoho-craftsaurus_brutipa)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0144', 'mk0006', '軽井沢ビール クラフトザウルス ブリュットIPA', 'st0104', 7.0, 35.0, 35, NULL, NULL, NULL, NULL, 'ヤッホーブルーイングが『軽井沢ビール クラフトザウルス』シリーズのブリュットIPA。カリフォルニア生まれのこのスタイルは、酵素の働きで糖度をほぼゼロまで切り詰める製法が特徴で、ホップの香りに辛口の飲み口が続く。ジャパン・グレート・ビア・アワーズ2021では銀賞を受けている。', 30.0, NULL, 'https://yohobrewing.com/products/craftsaurus_brutipa/', 'placeholder', 'https://yohobrewing.com/products/craftsaurus_brutipa/', NULL);

-- pr0145: 軽井沢ビール クラフトザウルス ペールエール (yoho-craftsaurus_paleale)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0145', 'mk0006', '軽井沢ビール クラフトザウルス ペールエール', 'st0004', 5.5, 37.0, 37.0, NULL, NULL, NULL, NULL, '『軽井沢ビール クラフトザウルス』シリーズのフラッグシップに位置づけられるアメリカンペールエール。ホップの香りを軸に据えた造りで、インターナショナル・ビアカップでは2017年・2018年に、ジャパン・グレート・ビア・アワーズでは2024年に、それぞれ銀賞を受けている。', 40.0, NULL, 'https://yohobrewing.com/products/craftsaurus_paleale/', 'placeholder', 'https://yohobrewing.com/products/craftsaurus_paleale/', NULL);

-- pr0146: 軽井沢高原ビール オーガニック (yoho-karuizawa_organic)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0146', 'mk0006', '軽井沢高原ビール オーガニック', 'st0097', 5.0, 20, 20, NULL, NULL, NULL, NULL, '有機麦芽と有機ホップを100%使用し、アファス認証センターの有機登録認定を受けた一本。コクと苦みのバランスに、すっきりとした爽やかな後味が続く飲み口に仕上げられている。「軽井沢高原ビール」ブランドの一銘柄として展開されている。', 30.0, NULL, 'https://yohobrewing.com/products/karuizawa_organic/', 'placeholder', 'https://yohobrewing.com/products/karuizawa_organic/', NULL);

-- pr0147: 軽井沢高原ビール 2026年限定 (yoho-karuizawa_year)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0147', 'mk0006', '軽井沢高原ビール 2026年限定', 'st0097', 5.0, 25.0, 25, NULL, NULL, NULL, NULL, 'ヤッホーブルーイングの『軽井沢高原ビール』シリーズが年ごとにレシピとスタイルを入れ替えて送り出す一本。今回はヒノキとカモミールが呼び起こすような、ハーブを思わせる香りに仕立てられている。毎年顔ぶれが変わるシリーズだけに、その年ごとの香りを味わうような性格の一本でもある。', 30.0, NULL, 'https://yohobrewing.com/products/karuizawa_year/', 'placeholder', 'https://yohobrewing.com/products/karuizawa_year/', NULL);

-- pr0148: 眠れるししし (yoho-nemurerushishishi)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0148', 'mk0006', '眠れるししし', 'st0028', NULL, 50.0, NULL, NULL, NULL, NULL, NULL, 'カテゴリーチャンピオンと金賞、二冠を手にしているのがこのバーレイワイン。舞台はインターナショナル・ビアカップ2025のブリティッシュスタイルバーレイワイン部門。購入後に自宅でじっくり寝かせる『ホームエイジング』を前提に設計されており、仕込まれる年によって立ちのぼる香味が少しずつ違ってくる。濃厚な味わいを、時間とともに育てながら楽しむ一本。', 50.0, NULL, 'https://yohobrewing.com/products/nemurerushishishi/', 'placeholder', 'https://yohobrewing.com/products/nemurerushishishi/', 'IBU_all');

-- pr0149: 山の上ニューイ (yoho-newee)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0149', 'mk0006', '山の上ニューイ', 'st0097', 4.5, 28.0, 28.0, NULL, NULL, NULL, NULL, '長野・山梨にルーツを持つ国産ホップを含む6種類を使い、水蒸気で香りだけを引き出す新製法『エッセンシャルホッピング』で仕立てた一本。ジャパン・グレート・ビア・アワーズ2025とコリア・インターナショナル・ビア・アワード2025で、ともに金賞を受けている。品種には『信州早生』『かいこがね』も含まれる。', 30.0, NULL, 'https://yohobrewing.com/products/newee/', 'placeholder', 'https://yohobrewing.com/products/newee/', NULL);

-- pr0150: そらとしば Play Ball! Ale (yoho-soratoshiba_playballale)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0150', 'mk0006', 'そらとしば Play Ball! Ale', 'st0087', 4.5, 20, 20, NULL, NULL, 1, NULL, 'インターナショナル・ビアカップ2023で金賞を受けた、セッションIPA。エスコンフィールドHOKKAIDO内のブルワリー『そらとしば by よなよなエール』の看板商品を、缶に詰めた一本である。青さを感じさせる香りが立ち、苦みはしっかりとした輪郭を持つ。', 50.0, NULL, 'https://yohobrewing.com/products/soratoshiba_playballale/', 'placeholder', 'https://yohobrewing.com/products/soratoshiba_playballale/', 'Fruity');

-- pr0151: 有頂点エイリアンズ (yoho-uchotenaliens)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0151', 'mk0006', '有頂点エイリアンズ', 'st0093', 6.0, 25.0, 25, 4, 4, 2, NULL, 'ヘイジーIPAというビアスタイルをより多くの人に知ってもらうことを狙って企画されたビール。大麦麦芽と小麦麦芽にオーツ麦を重ねた構成で、濁りを帯びた見た目とシルキーな口当たりをつくっている。香りはトロピカルな方向にまとまり、ジャパン・グレート・ビア・アワーズ2025では銀賞を受けた。', 50.0, NULL, 'https://yohobrewing.com/products/uchotenaliens/', 'placeholder', 'https://yohobrewing.com/products/uchotenaliens/', 'Color,Clarity,Fruity');

-- pr0152: 軽井沢高原ビール ワイルドフォレスト (yoho-wildforest)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0152', 'mk0006', '軽井沢高原ビール ワイルドフォレスト', 'st0005', 5.0, 24.0, 24, NULL, NULL, NULL, NULL, 'ヤッホーブルーイングの『軽井沢高原ビール』シリーズで定番として置かれるブロンドエール。麦芽とホップに小麦を加えて仕込まれ、しっかりとした飲みごたえと、するすると飲める軽さの両方を併せ持つ味わいに仕立てられている。軽井沢の名を冠したこのシリーズの、核となる一本と言える存在である。', 20.0, NULL, 'https://yohobrewing.com/products/wildforest/', 'placeholder', 'https://yohobrewing.com/products/wildforest/', NULL);

-- pr0153: 前略 好みなんて 聞いてないぜ SORRY 其ノ二 (yoho-zenryaku_umami)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0153', 'mk0006', '前略 好みなんて 聞いてないぜ SORRY 其ノ二', 'st0105', 6.5, 40.0, 40.0, NULL, NULL, 2, NULL, '和の素材と新しい発想を掛け合わせるシリーズ『前略 好みなんて 聞いてないぜ SORRY』の第二弾。小麦麦芽にコリアンダーシードとオレンジピールを重ねた土台に、かつお節から抽出したうま味成分を加えている。フルーティでホップの効いた香りに、まろやかな口当たりが続く。インターナショナル・ビアカップ2016で銀賞を受けている。', 45.0, NULL, 'https://yohobrewing.com/products/zenryaku_umami/', 'placeholder', 'https://yohobrewing.com/products/zenryaku_umami/', 'Fruity');

-- pr0154: 前略 好みなんて 聞いてないぜ SORRY 其ノ四 (yoho-zenryaku_yuzushio)
INSERT INTO `products` (`ProductID`, `MakerID`, `ProductName`, `StyleID`, `Alcohol`, `IBU_all`, `IBU`, `Color`, `Clarity`, `Fruity`, `Favorite`, `ProductExplain`, `IBU_Style`, `Comment`, `source_url`, `image_rights`, `official_url`, `estimated_fields`) VALUES ('pr0154', 'mk0006', '前略 好みなんて 聞いてないぜ SORRY 其ノ四', 'st0097', 4.5, 20, 20, NULL, NULL, 3, NULL, '柚子の香りに、あら塩の塩気がすっと効いて爽快な後味を残す一杯。使われているのはゆずの果皮と果汁、そしてあら塩。「前略 好みなんて聞いてないぜ SORRY」シリーズの第4弾にあたる一本である。', 30.0, NULL, 'https://yohobrewing.com/products/zenryaku_yuzushio/', 'placeholder', 'https://yohobrewing.com/products/zenryaku_yuzushio/', 'Fruity');
